# Generated by Django 5.0.3 on 2024-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state_name', models.CharField(max_length=70, verbose_name='State Name')),
                ('zip', models.CharField(max_length=6, unique=True, verbose_name='Zip Code')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
